# Generated by Django 6.1 on 2026-08-20 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0)),
                ('review_required', models.BooleanField(default=False)),
                ('classified_at', models.DateTimeField(auto_now_add=True)),
                ('predicted_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.category')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='AlternativeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.category')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.classificationresult')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.categoryattribute')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.classificationresult')),
            ],
        ),
    ]
