# Generated by Django 6.1 on 2026-08-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_brand_remove_product_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
