# Generated by Django 6.1 on 2026-08-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_model_number_product_product_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVIEW', 'Review'), ('APPROVED', 'Approved')], default='PENDING', max_length=20),
        ),
    ]
