# Generated by Django 6.1 on 2026-08-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('RETRYING', 'Retrying'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVIEW', 'Review'), ('APPROVED', 'Approved')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
